version: "2"
services:
  web:
    image: nginx:1.11.1
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    volumes_from:
      - php
    depends_on:
      - php
  console:
    image: registry.cn-hangzhou.aliyuncs.com/l_zero/console_php_7.1
    restart: always
    volumes:
      - ./application:/mnt/application
  php:
    image: registry.cn-hangzhou.aliyuncs.com/l_zero/php7.1
    restart: always
    volumes:
      - ./application:/mnt/application
  db:
    image: mariadb:10.1
    restart: always
    ports:
       - "3306:3306"
    volumes:
      - db_center:/var/lib/mysql
    environment:
      MYSQL_DATABASE : app
      MYSQL_ROOT_PASSWORD : root
      MYSQL_USER : app
      MYSQL_PASSWORD : admin888
      MYSQL_ALLOW_EMPTY_PASSWORD : 0
  ssdb:
     image: redis
     restart: always
volumes:
  db_center:
    driver: local
